### ISSUE TITLE
nexcloud 28 in docker - cant install from UI - runs wrong binary

### ISSUE THREAD

**Issue by rivendellstuff** [nextcloud/talk_matterbridge#101]
first time trying to set this up. 
have used mattermost for awhile now.
was hoping talk_bridge could help me migrate without having to actually make users switch to "talk". not sure if this is possible but wanted to see what the options are.

Anyway. I installed nextcloud and talk fine. All of that works. All of that is in docker with a standalone postgres database. 
I then use the UI to install talk_matterbridge.

it installs version 1.25 unless I switch my nextcloud off the stable channel. but even then or manual I get the same results:

`sh: 1: /var/www/html/custom_apps/talk_matterbridge/bin/matterbridge-1.26.0-linux-arm64: Exec format error`

I don't understand why its trying to run the arm64 version when my architecture i:s

`Linux 5f319cfff4ea 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64 GNU/Linux`

I've tried setting the binary manually using the command from the docs which executes fine but seems to make no difference:

`sudo docker exec --user www-data -it server-nextcloud php occ config:app:set spreed matterbridge_binary --value="/var/www/html/custom_apps/talk_matterbridge/bin/matterbridge-1.26.0-linux-64bit"`

I've tried installing manually, setting the binary, even renaming the AMD64 binary to the ARM one to trick it to running the correct one with no luck either. 

Am I doing something wrong or does this implementation just not work for Nextcloud Talk  when running in Docker?
thanks

Oh also note, the binary says its v1.26 even tho the tar file I downloaded was the 28 version and the app info confirms that, not sure if thats relevant or not

```
	<version>1.28.0-0</version>
	<licence>agpl</licence>

	<author>Gary Kim</author>
	<author>Julien Veyssier</author>

	<namespace>TalkMatterbridge</namespace>
```

**Comment by gary-kim** [comment]
Have you tried actually using it yet? The app tests running the arm version first then, if it does not run, tests running the amd64 version. The error message that you are seeing is expected on AMD64 systems so your install is likely already working.

**Comment by rivendellstuff** [comment]
> Have you tried actually using it yet? The app tests running the arm version first then, if it does not run, tests running the amd64 version. The error message that you are seeing is expected on AMD64 systems so your install is likely already working.

Hey thanks for the reply. 

How would I know if its working already? I expected a section for it in the settings but nothing ever shows up and no new config is added to my Nextcloud config.php.

Maybe theres no UI for setting this up?
I looked for a config file after enabling as well but didnt find one. Once I saw the error in the log I didnt look further as I thought it was failing there. 

I'll go through this then if the log error is expected: https://github.com/42wim/matterbridge/wiki/How-to-create-your-config 

I'll add that that error is misleading in such a case then, might be good to update that cuz once I didnt see any new config or new UI options for it, I checked the log to ensure it installed correctly. Seeing that error sent me down the troubleshooting path instead of trying to config it since I thought it was broken.

Thanks! I'll report back if its still not working after manually creating the config.

**Comment by rivendellstuff** [comment]
I couldnt get it to work by installing matterbridge in nextcloud.
i did manage to get it to work standing up matterbridge in its own docker container and its much easier to troubleshoot when logs are avail now!

Maybe I'm not clear about the functionality tho.
If my bot is added to the channel its can relay messages between mattermost and talk. But if I have a one on one conversation with someone, the bot isnt part of that so it fails to start that gateway. Its cool that it works for channels. I have mostly private messages between users so I dont think this is the right path for what I need.

Thanks again.
