### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by henrysheehy** [nextcloud/talk_matterbridge#106]
Having installed this through the NextCloud app store, how does one then interact with it?

I see no information available.

Thank you.

**Comment by henrysheehy** [comment]
I assume it is not compatible with the latest NextCloud.

**Comment by lukaszsobala** [comment]
I've been trying to enable this in some conversations on Talk but there are no options for Matterbridge anywhere.

**Comment by henrysheehy** [comment]
Seems to be working now. It's done through chat bots.
