### ISSUE TITLE
Duplicated messages when using Bigbluebutton plugin in mattermost

### ISSUE THREAD

**Issue by makayabou** [nextcloud/talk_matterbridge#11]
I'm using Nextcloud 20.0.9 with Keycloak ass SSO provider, connected with OpenID Connect Login.

I use talk-matterbridge plugin to connect to a mattermost instance.

Problem is when I run a bigbluebutton session in mattermost, using bigbluebutton session. 

I get a lot of repeated messages about it in my bridge chatroom.

![Capture d’écran de 2020-10-15 01-46-53](https://user-images.githubusercontent.com/25554584/96057888-3f95f500-0e8a-11eb-8b94-f76215e948aa.png)

**Comment by gary-kim** [comment]
Do you still have this issue? This is most likely an upstream issue in Matterbridge.

**Comment by makayabou** [comment]
I couldn't tell, I switched to Element

**Comment by gary-kim** [comment]
Okay, I'm going to close this for now. Feel free to reopen if you need it.
