### ISSUE TITLE
Starting gateway failed (double slash in URI)

### ISSUE THREAD

**Issue by dst21** [nextcloud/talk_matterbridge#15]
Hello,

I have set up the matterbridge between Nextcloud Talk and Telegram, but I get the error that the bridge could not be started. The reason here will be that there will be two // after the domain, but I don't know how they get there:

level=info msg="Running version 1.19.0 2bb21262" prefix=main
level=info msg="Parsing gateway myGateway" prefix=router
level=info msg="Starting bridge: telegram.0 " prefix=router
level=info msg=Connecting prefix=telegram
level=info msg="Connection succeeded" prefix=telegram
level=info msg="telegram.0: joining  (ID: telegram.0)" prefix=telegram
level=info msg="Starting bridge: nctalk.1 " prefix=router
level=info msg=Connecting prefix=nctalk
level=error msg="Cannot Connect" prefix=nctalk
level=fatal msg="Starting gateway failed: Bridge nctalk.1 failed to start: Get "https://cloud.domiain.com//ocs/v2.php/cloud/capabilities": dial tcp <ip>:443: connect: connection timed out" prefix=main

Maybe someone can help me here?

**Comment by gary-kim** [comment]
Oh, is the double slash an issue for you? I'm realizing I didn't put enough care into making sure there were no double slashes in requests. I'll work on this.

**Comment by dst21** [comment]
After your answer, I thought of something and I checked it again. It was due to my configuration with reverse proxy. Nevertheless, double slash problems can cause problems, even if in the case this was probably not directly due to them.

**Comment by dst21** [comment]
Now I still get the following error. Maybe it's related to this?

level=error msg="SendMessage failed: strconv.ParseInt: parsing "": invalid syntax" prefix=gateway

**Comment by gary-kim** [comment]
The original issue should have been addressed by newer updates now.
