### ISSUE TITLE
[Enhancement] Support also other architectures

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/talk_matterbridge#18]
I tried to install talk_matterbridge. In Apps it seems like talk_matterbridge is installed, but I'm still getting the option for installing talk_matterbridge in the App settings. So I tried to remove the App and install it again (this time in the terminal). I'm getting an error while installing:
```
$ sudo -u www-data php occ app:install talk_matterbridge
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.19.0-linux-32bit: Permission denied
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.19.0-linux-32bit: Exec format error
talk_matterbridge 1.19.0 installed
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.19.0-linux-32bit: Exec format error
sh: 1: /var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.19.0-linux-32bit: Exec format error
talk_matterbridge enabled
```
tallk_matterbridge does not support armv6 and many other architectures, which are already supported by matterbridge. Please provide also binarys for armv6 and other architectures supprted by matterbridge.

**Comment by LunkSnee** [comment]
@sirdrakeistda - what is your platform? are you running nextcloud on linux, 32bit?

**Comment by sirdrakeistda** [comment]
I run Nextcloud on a raspberry Pi. The 32 image didn't worked. After Updating to arm 64 I tried the arm 64 image (it worked). It seems like only the 32 Bit image has Problems.

04.01.2021 01:48:09 LunkSnee <notifications@github.com>:

**Comment by sirdrakeistda** [comment]
For all Raspberry Pi User:
The 32-bit image does not work on the Raspberry Pi, because the image does not support armv6. If you want to setup it on a raspberry Pi you have to use either a 64-bit Image on the Raspberry Pi (only possible for Raspberry 2 v1.2 and higher, processor needs to support 64-bit). Or run matterbridge with the original armv6 binary (I haven't tried the integration in Nextcloud, but running "external" should work, e.g. with docker on the same Pi).
https://github.com/42wim/matterbridge/releases

So updated issue:
Please support all architectures which are already supported by matterbridge.

**Comment by sunjam** [comment]
> Please support all architectures which are already supported by matterbridge.

Same issue as duplicate #67 because only architecture mentioned is 32-bit.

32-bit support has reached [EOL with Nextcloud 24 on 5/2023](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule).  Current 25.0.0 stable is not supported at all, [plus 64-bit is now mandatory in the official system requirements](https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html).
