### ISSUE TITLE
How do I use this App?

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/talk_matterbridge#33]
I found this app in Nextcloud apps but I do not get how I could use this app. There are no settings to set and I do not know what you mean with matter bridge binary. Does it also work if I only could run php and some bash scripts on a shared web host?

**Comment by gary-kim** [comment]
This app is meant to be used with [Nextcloud Talk](https://apps.nextcloud.com/apps/spreed). It allows you to use the bridging features of Nextcloud Talk.

**Comment by Mannshoch** [comment]
Hi @gary-kim that is the only point I already know because it is clearly described in the description of the app.
What's with the other points?

**Comment by gary-kim** [comment]
The app exists purely to let admins easily install [Matterbridge](https://github.com/42wim/matterbridge) binaries from the Nextcloud web interface.
