### ISSUE TITLE
Matterbridge config file location

### ISSUE THREAD

**Issue by greavette** [nextcloud/talk_matterbridge#46]
Hello,

Matterbridge version : 1.22.1

I'm using the fields in Nextcloud Talk > Settings to enter in the details needed for Matterbridge.  Are these settings saved to a file?  If so where in Nextcloud is the location of this file?  I've looked at the documentation and I can see reference to the file but I can't find this on my Nextcloud.

Thank you.

**Comment by gary-kim** [comment]
They are in the `/tmp` directory.

https://github.com/nextcloud/spreed/blob/3a3b7d0bcbe4b1f69db7731bc7e5bc2779f088fb/lib/MatterbridgeManager.php#L695

Also, this is an issue tracker meant for bugs and feature requests. Please go to https://help.nextcloud.com to ask questions.
