### ISSUE TITLE
talk_matterbridge chooses wrong binary

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/talk_matterbridge#55]
I run nextcloud on a raspberry pi. Every time after update the 32-bit image is choosed automatically, but it does not run (for matterbridge there is an extra arm 32-bit binary and my raspberry pi runs 64-bit, so it should choose arm64). I have to switch manually back to the arm64 binary.

**Comment by gary-kim** [comment]
Are you running a armv7 PHP version by any chance? We use the `PHP_INT_SIZE` to determine if the device is a 32 or 64 bit device:

https://github.com/nextcloud/talk_matterbridge/blob/40ee746d2aea89d473ed8d14eb7c577e681f59e6/lib/Migration/RegisterBinary.php#L50

**Comment by sirdrakeistda** [comment]
My Raspberry has an armv8 Processor, otherwise it wouldn't be possible to run a 64 bit system. Is there a possibility to check or change the PHP_INT_SIZE value?

**Comment by sirdrakeistda** [comment]
You are right. My php Version is 32-bit. I'm not sure why and how to change it.
