### ISSUE TITLE
Support Nextcloud 24

### ISSUE THREAD

**Issue by Kitanit** [nextcloud/talk_matterbridge#69]

**Comment by Kitanit** [comment]
interesting
![image](https://user-images.githubusercontent.com/65107731/168229001-0a73bbd5-e0d0-4cc9-b49c-95cb60a77fd7.png)
![image](https://user-images.githubusercontent.com/65107731/168229033-25371797-c483-4008-ac17-df5764a4fd5c.png)

**Comment by nickvergessen** [comment]
@gary-kim any change?

**Comment by gary-kim** [comment]
Will test today
