### ISSUE TITLE
Upgrade to Binary version 1.26

### ISSUE THREAD

**Issue by yuisheaven** [nextcloud/talk_matterbridge#95]
Hello there!
I've had a look at the source code - originally to figure out why it sometimes doesnt show me the registered and active bridges which is another bug.. - and noticed that the Binary version in RegisterBinary.php is set to '1.25.2' which is one version off. 
There's a new version 1.26 which fixed quite a few things and I wanted to ask if it is possible to upgrade.

Best regards

**Comment by mhzawadi** [comment]
yes please
